### ISSUE TITLE
EXC_BAD_ACCESS Crash when starting plugin on ios

### ISSUE THREAD

**Issue by lallutin** [adjust/unity_sdk#119]
Unity: 5.6.5f1
XCode: 9,2
Adjust: 4,12,1

When starting the plugin manually i get exception from the line in AdjustUnity.mm(77)
`NSString *stringUserAgent = [NSString stringWithUTF8String:userAgent];`

**Comment by uerceg** [comment]
Hi @lallutin 

Thanks for reporting, we're onto this, will keep you posted in here.

Are you seeing this happening with iOS 10 only or with iOS 11 as well?

**Comment by uerceg** [comment]
Also, can you share with us code you use to initialise SDK?

**Comment by uerceg** [comment]
@lallutin 

Thanks! Would like to hear if you are facing same issue with iOS 11.

**Comment by lallutin** [comment]
ios 11 works as expected

**Comment by uerceg** [comment]
@lallutin 

Interesting. Thanks for reporting, we're investigating and will keep you posted.

**Comment by uerceg** [comment]
@lallutin 

Would it be possible to send us full stack trace of exception that happens in iOS?

**Comment by uerceg** [comment]
@lallutin 

Is this something you can reproduce in empty example app as well? If yes, can you make one and just attach it in here, since we can't reproduce the issue even if we try your environment setup. If you can attach it, again feel free to obfuscate sensitive parts.

**Comment by uerceg** [comment]
@lallutin 

Can you give this SDK version a try and let us know if it solved your problem? We have just renamed `.unityarchive` to `.zip` so that Github allows it to be attached in here. Once you download it, just change extension from `.zip` back to `.unitypackage`. This is our next SDK update RC, so nothing official at the moment. Looking forward to hear from you on this.

Cheers

[Adjust_v4.12.2-RC1.zip](https://github.com/adjust/unity_sdk/files/1704170/Adjust_v4.12.2-RC1.zip)

**Comment by lallutin** [comment]
Seems to be working. 

Can we use this in a release build or should we wait for the actual release?

**Comment by uerceg** [comment]
@lallutin 

Great, glad it worked for you. 👍 

Official version is going to contain one additional thing that will solve some issues when users try to run their apps in Editor and execute Adjust SDK code from there. We are probably going to release it by tomorrow, so if you are in no rush, you can wait for official release.
