### ISSUE TITLE
Can't compile for webGL because of incorrect plugin import setting

### ISSUE THREAD

**Issue by Seb-degraff** [adjust/unity_sdk#128]
The plugin Adjust.a should be included only in the iOS build.

Thanks!

Current import settings:
<img width="346" alt="capture d ecran 2018-03-06 a 16 03 50" src="https://user-images.githubusercontent.com/6556843/37039638-4292b99a-2158-11e8-9f9f-04ad00fc2e6a.png">

Should be:
<img width="345" alt="capture d ecran 2018-03-06 a 16 03 40" src="https://user-images.githubusercontent.com/6556843/37039637-4275eea0-2158-11e8-9061-0952365da115.png">

**Comment by uerceg** [comment]
@Seb-degraff 

Thanks for pointing this out. Can you maybe give our Unity plugin from this comment a try and let us know if it solved your issues? If yes, we're gonna update it in our releases page for latest release.

Since `.unitypackage` file format is not attachable to Github, I have simply renamed it to `.zip` so after downloading it, just change extension back to `.unitypackage` before importing it to your project.

Cheers

[Adjust_v4.12.3.zip](https://github.com/adjust/unity_sdk/files/1788124/Adjust_v4.12.3.zip)

**Comment by uerceg** [comment]
Hi @Seb-degraff 

We have released an update of Adjust Unity SDK v4.12.4 which should address this issue: https://github.com/adjust/unity_sdk/releases/tag/v4.12.4

Feel free to reopen the issue in case you still encounter this issue with v4.12.4++.

Thank you one more time for reporting the issue.

Cheers!
