### ISSUE TITLE
Attribution Callback missing data?

### ISSUE THREAD

**Issue by channingcorn** [adjust/unity_sdk#131]
I'm not seeing some data in the attribution callback in Unity. The fields missing are:
**campaign
ad_group
creative
click_label**

`{`
  `   "tracker_name": "Happy Installs",`
  `   "tracker_token": "abcdef",`
  `   "network": "Happy Installs",`
  `   "campaign": "",`
  `   "ad_group": "",`
  `   "creative": "",`
  `   "click_label": "",`
  `   "adid": "a123456789abb1abcc1223334445de99"`
`}`

Is this expected?

**Comment by uerceg** [comment]
Hi @channingcorn 

SDK populates fields in attribution callback which we have obtained in the attribution response from our backend. The fields you've got (non-empty string ones) are the ones that are part of the attribution for this particular install and probably source to which this install was attributed didn't contain `campaign`, `adgroup`, `creative` and `click_label` set. In order to have these populated, you would need to have those defined in, for example, tracker URL you're clicking before making an install. For example:
```
https://app.adjust.com/abc123?adgroup=dummy&creative=dummy&network=dummy&campaign=dummy
```
This should cause your attribution callback to contain:

- Tracker token (since you have made `abc123` in your dashboard, for example).
- Tracker name (since you've named that tacker)
- Network (since it's defined in URL as a parameter with value dummy)
- Adgroup (since it's defined in URL as a parameter with value dummy)
- Campaign (since it's defined in URL as a parameter with value dummy)
- Creative (since it's defined in URL as a parameter with value dummy)
- Empty click label, since none was defined.

**Comment by uerceg** [comment]
@channingcorn 

Any update on this one?

**Comment by channingcorn** [comment]
I believe everything is working now.
