### ISSUE TITLE
iAd.framework is deprecated

### ISSUE THREAD

**Issue by nightrise** [adjust/unity_sdk#132]
Hi there,

The documentation in the README.md says that the iOS Post Build Process adds iAd.framework to the xcode project.

However, neither Unity nor Apple support iAd.framework any longer: https://developer.apple.com/support/iad/

Is this information still accurate?

**Comment by uerceg** [comment]
Hi @nightrise 

We had this question a while ago in our iOS SDK repo: https://github.com/adjust/ios_sdk/issues/196.

Our post build process for iOS adds it by default, since it tries to enable all features our SDK supports. In case that you are not running Search Ads campaign for your app, you don't even need this framework and you can feel free to remove it from your app.

**Comment by nightrise** [comment]
Thanks for the quick response, and link! That answers my question.
