### ISSUE TITLE
Reattribution via deep links

### ISSUE THREAD

**Issue by dotlut** [adjust/unity_sdk#143]
Hello, I would like to know about "Reattribution via deep links" when using the **unity_sdk**.

I saw these guidelines:
Android https://github.com/adjust/android_sdk#deeplinking-reattribution
iOS https://github.com/adjust/ios_sdk#deeplinking-reattribution

Both inform that deep links should be handled in native code.

Question:
I would like to know if the **unity_sdk** v4.17.0 supports "Reattribution via deep links" by default?

If not:
It would be necessary to add the call to appWillOpenUrl on both native iOS and Android as said on both links above?

My context:
Currently, we have **unity_sdk* version v4.11.4 in our project.

**Comment by uerceg** [comment]
Hi @dotlut,

This is unfortunately something you should (for now, we might try to add support for this in the future in the SDK itself) handle from native side. From what we know, Unity still doesn't support forwarding of links which have opened an app from native to Unity layer (if you maybe know that support for this exists, please let us know so that we can update the docs). With this in mind, one needs to capture link which opened an app in native layer - in `AppDelegate` of your iOS app or inside of intent in `Activity` in Android which handles scheme from your link. Once those links are obtained in there, you can in theory do two things:

1. Simply invoke `appWillOpenUrl` method from native Adjust SDK code from those places or
2. You can build your own mechanism of dispatching that natively received link into Unity layer and then make a call to `Adjust.appWillOpenUrl` method from Unity layer.

How ever you want.

We wanted to add support for this inside of our SDK, but in order to do that, we would need to do certain things which we found as troublesome and kinda pretty intrusive (which we saw other plugins are doing, but to us it just sounds wrong):

- We would need to override/extend/enforce native `AppDelegate` class with our custom implementation of it which will handle links which are opening your app and dispatch that information to Unity layer for our SDK to get it.
- We would need to do the same thing for Android activity which would be the one in charge for handling URL scheme from your link as well.

It's doable, beyond any doubt, but even though Unity developers tend not to mess around with native code that much and this approach might even be unnoticed to many of developers, we just think it's too spooky. We also saw lots of plugins which are doing this that they don't even include even basic logic for checking if Unity app already has default implementation of those native classes overridden/changed/extended, but are rather simply not caring too much and enforcing their custom implementations. If app would be using multiple plugins which are behaving like that (including ours, even if we try to make some more advanced logic that simply forcing things), it could still be pretty possible that those other plugins would force their solution and then this forwarding of things from native layer to Adjust SDK in Unity layer might get broken and won't work, which then opens the door of endless issues being reported and support hell we need to handle.

So for now, this is how things are. We are monitoring this topic and maybe we'll come up with some better solution than current one or maybe Unity will pay attention to this part of ecosystem and maybe provide an option for Unity apps to be notified in Unity layer about links which have opened an app.

For this approach, I would advise you to update to latest Unity SDK, since a bit improved support for this use case exists as of SDK v4.14.0 and if you are already updating SDK, we always advise to use the latest version.

In case you have any further questions, feel free to ping us in here.

**Comment by uerceg** [comment]
@dotlut 

Do you need any further assistance on this one?

Cheers

**Comment by dotlut** [comment]
Hello @uerceg 

First, thank you for the very clear reply, it helped a lot!

As we already have unity_sdk on our project, we are considering these two possibilities:

1. Use native calls to Adjust.appWillOpenUrl on both iOS and Android while having unity_sdk
    - Here, we have the drawback that the lib is being initialised on Unity and this can be a problem. As an example, if our app is opened by an intent, the Adjust lib was not yet initialised when onCreate is called.
    - Solution: Apparently, it is possible to initialise it by hand. So, we could make it on the native side before onCreate being called. I’m not really sure about this.

2. Use sendMessage to notify Unity of the received deep-links
    - Here, the only downside is that it will be necessary to buffer the deep link and recover it later, because Unity may not be ready to receive the message when the deep-link arrives.

I think we are going to proceed with the second one, however if you have any extra advise on it, it will be very welcome!

Cheers

**Comment by uerceg** [comment]
Hi @dotlut 

We actually started to anticipate this situation a while ago and have updated our native SDK to actually do the caching of links passed to `appWillOpenUrl` method into user defaults / shared preferences. So you can feel free to proceed with step 1 as well because even though call to `appWillOpenUrl` will happen on native side way before Unity engine actually initialises SDK, these links will not be lost and SDK should look for any cached stuff upon it's initialisation and send them over to our backend in case any is found.

You can even give this a try, since it's not big work to add it to your app. Just make sure you're using latest Unity SDK of ours, just in case.

Lemme know if it worked for you. Of course, if you still think 2nd option is better way to go, feel free to use that path - it should work as well.

Cheers

**Comment by uerceg** [comment]
Hi @dotlut 

Anything else needed on this one?

Cheers

**Comment by dotlut** [comment]
Hi @uerceg , sorry for the late reply

No, we managed to successfully update Adjust on our project. Thank you very much for your help!

Cheers!
