### ISSUE TITLE
WUP on unity 5.3.6 compile error

### ISSUE THREAD

**Issue by e1iman** [adjust/unity_sdk#157]
Hey, we are integratin adjust to all our projects, we use mostly 2017+ unity version with il2cpp scripting backend.

All platforms are working fine, but integrating adjust sdk to project that is runing on Unity 5.3.6f1 .Net (10.0.14393.0 .net version)  we have compile error on WUP 10+

also one of the problems is that dll import settings uses newest serialized options, so importing them on old version of unity has empty import settings (but we just copy them)
```
 Failed to fix references for method System.String AdjustSdk.Uap.UtilUap::GetDeviceType(Windows.Security.ExchangeActiveSyncProvisioning.EasClientDeviceInformation)
1>  Failed to fix references for type AdjustSdk.Uap.UtilUap
1>  System.ArgumentNullException: Value cannot be null.
1>  Parameter name: type
1>     at Mono.Cecil.ModuleDefinition.ImportReference(TypeReference type, IGenericParameterProvider context)
1>     at Mono.Cecil.ModuleDefinition.ImportReference(TypeReference type)
1>     at Unity.ModuleContext.Retarget(TypeReference type, GenericContext context)
1>     at Unity.FixReferencesStep.Visit(MethodDefinition method, GenericContext context)
1>     at Unity.FixReferencesStep.Visit(TypeDefinition type)
1>     at Unity.TypeDefinitionDispatcher.DispatchType(TypeDefinition type)
1>     at Unity.TypeDefinitionDispatcher..ctor(ModuleDefinition module, ITypeDefinitionVisitor visitor)
1>     at Unity.FixReferencesStep.ProcessModule()
1>     at Unity.ModuleStep.Execute()
1>     at Unity.FixReferencesStep.Execute()
1>     at Unity.Step.Execute(OperationContext operationContext, IStepContext previousStepContext)
1>     at Unity.Operation.Execute()
1>     at Unity.Program.Main(String[] args)
```

// this is happening on empty unity project

**Comment by uerceg** [comment]
Hi @e1iman 

Thanks for reporting it, will be addressed soon! Will keep you posted.

Cheers

**Comment by uerceg** [comment]
Hi @e1iman 

Wanted to ask you which OSX version are you using? We are mostly on OSX 10.15 already which offers no support for Unity 5, but even though we're having some machines on OSX 10.14 where Unity 5.x.y can be installed, we're seeing that we absolutely can't make several version we tried to run at all.

For example Unity 5.0.0 and 5.0.1 do start (which is nice), but if one tries to import or even manually paster stuff to Assets folder, IDE never shows any of the file/folders in Asserts. Unity version you reported (5.3.6) and latest version of 5 out there also did install, but when we launch them, they are just stuck on first dialog (should be project explorer) which is just totally grey and doesn't show anything. So seems like we're currently out of options to run Unity 5, this is probably the reason you saw the issue, since we built last version with last 2017 LTS version.

**Comment by e1iman** [comment]
to reproduce , you should run on windows machine. Only on windows unity will have option to switch target platform to windows store

**Comment by uerceg** [comment]
Gotcha, thanks for info.

**Comment by uerceg** [comment]
Hi @e1iman 

Here's RC (needed to ZIP it in order to attach it in here) of our next Unity SDK release (which might wait a bit for after Xmas holidays), but would like to hear from you if it solves your issue. If yes, great news and we will most probably release next version out of that unity package.

Looking forward to hearing from you.

Cheers
[Adjust_v4.19.1_RC1.unitypackage.zip](https://github.com/adjust/unity_sdk/files/3973644/Adjust_v4.19.1_RC1.unitypackage.zip)

**Comment by neanton** [comment]
Still does not work with Unity 5.3.6 when building for UWP. Check please

**Comment by uerceg** [comment]
Hm. Pretty weird. Just tried it with UWP on Unity 5.2.0 on Windows and got the project built without any errors. Will try to check it.

**Comment by neanton** [comment]
@e1iman maybe you can attach zipped Unity project where this issue is reproduced?

**Comment by e1iman** [comment]
[adjust.zip](https://github.com/adjust/unity_sdk/files/3977568/adjust.zip)

**Comment by uerceg** [comment]
Thanks, we'll try this in Unity 5.3.6f1 on Windows to see if we can reproduce the error.

**Comment by e1iman** [comment]
hey, any status update?:)

**Comment by uerceg** [comment]
Hey, unfortunately still not. We are on it, but so far we were unable to reproduce the error you reported. Still investigating, will report in here what did we manage to see that is happening after trying out few more things today.

**Comment by uerceg** [comment]
Sorry for delay, but I was not able to reproduce the error you guys are facing. We needed to push the [4.19.1 release](https://github.com/adjust/unity_sdk/releases/tag/v4.19.1) to address another issue, I'd be curious to hear from you if same issue is still there with that version?

**Comment by e1iman** [comment]
still same issue, what Windows Universal SDK you are on? when building on unity 5.3.6?

**Comment by uerceg** [comment]
Hm. To be honest, I was unable to reproduce it. I originally tried to test Unity 5.2.0 where UWP support was initially introduced and didn't see the error, but now I tried 5.3.6 (f1 and p3) and honestly I was unable to make anything work. Project was unable to be built, but not with this error at all, but rather due to failure to resolve some internal .NET DLLs and I didn't really have time to check out how to make it work. Unity 5 version we're using to build our package and check if projects are buildable is pretty much latest Unity version out there - 5.6.7 and when building in there, this is the UWP SDK version I use:

![UWPSDK](https://user-images.githubusercontent.com/1741635/72072976-4b4afe80-32ef-11ea-857b-b8ec64b2bd84.png)

This is the project from that Unity version if it means anything to you:

[AdjustExample.zip](https://github.com/adjust/unity_sdk/files/4040655/AdjustExample.zip)

Also for the record, in few months to come, we're gonna drop Unity 5 support completely. We're about to publish SDK to Asset Store and publishing in there can be done only from Unity 2017 and later, so we're probably gonna sunset support for Unity 5, WS81 and WP81 platforms.

**Comment by uerceg** [comment]
If needed, feel free to comment in here further or reopen. Cheers.
