### ISSUE TITLE
Incorrect import settings for iOS native files

### ISSUE THREAD

**Issue by fliperamma** [adjust/unity_sdk#171]
Native files inside the `iOS/Test` folder have import settings' platform as `Android` and not `iOS`.

**Comment by uerceg** [comment]
Hi @fliperamma 

Thanks for reporting. In which Unity SDK version did you encounter `Test` folder and where did you download it from?

**Comment by fliperamma** [comment]
Sorry @uerceg we are rushing to have this fixed.

**Unity 2019.2.21f**

Downloaded here

https://github.com/adjust/unity_sdk/releases/tag/v4.20.1

**Comment by fliperamma** [comment]
Yeah, it seems that removing the folder would fix both issues. :)

**Comment by uerceg** [comment]
Yeah, definitely, but just for the record, I'm somehow doubtful that you might ended up with this folder maybe from 4.20.0 build (if you have used it, since 4.20.1 was actually released to fix this issue).

This is how it looks like if I try to import 4.20.1 version into Unity app:

<img width="806" alt="Screenshot 2020-04-01 at 12 37 38" src="https://user-images.githubusercontent.com/1741635/78128159-bc451280-7415-11ea-9974-df10338075dc.png">

So there's no `iOS/Test` folder which makes me think of what I wrote above. Nevertheless, the folder should not be there, so regardless of where you have "picked it up on the way", feel free to remove it from any folder you might find it present (`iOS/Test`, `Android/Test`, `Windows/Test`, even in `Assets/Adjust/Test`) and things should be fixed.

**Comment by fliperamma** [comment]
Thanks a lot @uerceg. Yeah that makes sense, will try building again, but I'm pretty sure it will fix the issue. Thanks again! ⭐️
