### ISSUE TITLE
some Regular APIs for Analytics SDK is NOT exposed in Unity C# API

### ISSUE THREAD

**Issue by CodeMasterYi** [adjust/unity_sdk#180]
As the title!
like SetUserId?
like UpdateUserProperty or SetUserProperty?

**Comment by uerceg** [comment]
Hi @CodeMasterYi 

To be honest, not really sure what is exactly the semantics of each of these methods you are mentioning. Even for those analytics SDKs which have them, they are used what ever the actual analytics provider is using them for.

We don't have methods named like that because either:
- We don't support/need that feature in our platform.
- We named the method somehow else.

If you can explain maybe what those methods (and features behind them) are supposed to do, maybe I can point you to already existing feature of our platform.

**Comment by CodeMasterYi** [comment]
Sorry, maybe I don't really understand Adjust after studying facebook analytics & firebase analytics～

**Comment by uerceg** [comment]
No worries. Like said, if you can maybe explain us what exactly are you trying to do, we might be able to help you by pointing to some already existing feature in our platform. Or if we can't, then you can always ping our support team.

**Comment by CodeMasterYi** [comment]
Emmm... ignore what i said

**Comment by uerceg** [comment]
Sure thing. Any need for issue to still be opened or can we close it?
