### ISSUE TITLE
Using Adjust SDK with Oculus Go/Quest Apps

### ISSUE THREAD

**Issue by HebaMohamed** [adjust/unity_sdk#181]
Hello team,

We are trying to use adjust sdk with our oculus go app, but according to the quick start instructions , adjust sdk needs the `google advertising id` which require integrating `google play services` and that cannot be done on the oculus go/quest apps according to [oculus distribution instructions ](https://developer.oculus.com/distribute/publish-uploading-mobile/)

> You cannot rely on Google Play Services (e.g. Google Firebase, Google Cloud Messaging, etc), or third-party libraries that depend on Google Play Services (e.g. OneSignal) when running on Oculus Go or Quest.

So there is any way to still use adjust sdk without the google advertising id ?

**Comment by uerceg** [comment]
Hi @HebaMohamed 

Presence of Goofle Advertising Identifier is not at all mandatory for Adjust SDK to work. From SDK point of view, that's just a parameter which, if conditions for us to read it are met, will be read (and sent to our backend) or not. But SDK's functionality doesn't rely on presence of that parameter.

Reason why that parameter is important is because most of the advertising campaigns are ran these days based on that identifier and it's needed to match click on advertisement with install which that click drove (for example). Without it - possibilities of performing attribution are becoming pretty slim. 

So at the end of the day, question comes down to what do you really want to use Adjust SDK for. If potential limitation I described is something which you don't really care about, all good. If not, then it might be problem.

Saying might because adding this dependency in a way described in README is actually a way which our SDK uses as fallback mechanism when trying to read Google Advertising Identifier. Main mechanism doesn't require it, but problem with any of the approaches used to read it is that Google made this API to obtain the value via service connection under the hood, so mechanism itself is not guaranteed to return value of identifier. This is why we have  both mechanisms in place, to reduce number of cases where we might end up not reading the parameter to minimum. If you don't follow the README, you would be leaving SDK without fallback mechanism and that's mostly it. Main mechanism should still try to read it and from what we saw in our data, this way actually is the one which reads the identifier in 97-99%+ of cases. You can try integrating SDK, setting it to sandbox environment, log level to verbose and check logs with tag Adjust. When ever SDK is about to track something, it prints the list of parameters tracked with that package. If you see gps_adid in there, we read it. You can give it a shot.

I am wondering what does that quote mean when it says rely. Is it rely that anything from Google Play Services can be used or something else, not sure. Because I am not sure if there is something which prevents you from adding this dependency to you app (at the end of the day you are adding JAR/AAR to your Assets folder and that's the same thing which our plugin does with placing our SDK JAR to Assets/Adjust/Android folder). Sounds to me like it should be doable, but never had experience with Oculus apps development in Unity.

In case you have any further questions, feel free to ping.

Cheers

**Comment by uerceg** [comment]
In case there's any need to reopen, feel free to, also if you have any further questions, feel free to ping.

Cheers

**Comment by Dong-Hwi-Lee** [comment]
So, one more question: If you don't use the Google Play Store service, don't you need to add related libraries to your project?
