### ISSUE TITLE
Using Adjust SDK with Oculus Go/Quest Apps

### ISSUE THREAD

**Issue by Dong-Hwi-Lee** [adjust/unity_sdk#186]
Hi, Adjust Unity SDK Team

I developed the Oculus app in Unity Project and registered it in Oculus Store.

Currently, I want to import and use the Adjust SDK for this project.

However, in the case of the Android platform, we were informed that we cannot use apps that are not registered on Google Play Store.

Is there a way to use the Adjust SDK for Android apps registered in Oculus Store?

When I read the Adjust Unity SDK document, it seems that there is an operation to insert the Google Play-related library directly into Asset/Adjust/Android. I also carried out this.

First of all, the Adid value appears to be NULL, and only the failed callback called Invalid Event Token is shown.

I wonder why Android-based apps that are not registered in Google Play Store cannot use the Adjust SDK.

**Comment by uerceg** [comment]
Hi @Dong-Hwi-Lee 

This issue seems like duplicate-ish of [this](https://github.com/adjust/unity_sdk/issues/181)?

Also information that you need to have app which is published in Google Play Store in order to use Adjust SDK is not true. Our SDK is pretty much store agnostic and it runs inside of the app as long as app is running Android operating system (or Fire OS from Amazon). So you can add and use our SDK to pretty much any Android app.

Regarding Google Play Store library dependency, it's described in issue I linked above.

`adid` value in SDK is `null` as long as SDK doesn't successfully track first session, after that we get `adid` value from our backend and SDK has it at its disposal. For the record `adid` stands for Adjust Identifier, so it's internal device identifier for Adjust.

Invalid event token error you might be seeing since you're creating event with event token which doesn't exist for your app in Adjust dashboard. Have you created event in dashboard and used that token in your app?

Sharing SDK initialisation and usage code in your app + SDK verbose logs (set SDK to sandbox environment and log level to verbose) would be useful to see what's happening in your app. Feel free to remove any sensitive information from the logs which you might not want to see shred in public.

Cheers

**Comment by Dong-Hwi-Lee** [comment]
So, one more question: If you don't use the Google Play Store service, don't you need to add related libraries to your project?

**Comment by uerceg** [comment]
Yes, you don't need to add it if you don't need it. That is needed for usage of Google Advertising Identifier from your users which you might later use for user acquisition purposes. Then again, if your app is published outside of Google Play Store, not sure if collection of Google Advertising Id makes any sense to you at all. So probably perfectly fine if you don't add it to your app.

**Comment by Dong-Hwi-Lee** [comment]
Yes, then is there no reason why Adjust SDK won't go back to Oculus?

This is how I set up and how to use the callback parameters within Unity.

First of all, Adjust.cs.
AdjustConfig adjustConfig = new AdjustConfig ("idjfm2gbksdlsdls", environment, (logLevel == AdjustLogLevel).Suppress);
adjustConfig.setAppSecret (2, 978456465, 1264564658, 1261564412, 1165456453);
adjustConfig.setEventFailureDelegate (EventFailureCallback);
adjustConfig.setEventSuccessDelegate (EventSuccessCallback);
Adjust.start (adjustConfig);

The app token, and app secret information shown here cannot be disclosed, so it is virtual information.

After that, we make a singleton of AdjustManager.cs function and use a callback parameter.

public void EnterMoviePlayScreen()
{
AdjustEvent adjustEvent = new AdjustEvent ("EnterMoviePlayScreen");
AdjustEvent.addCallbackParameter ("play_id", "123456");
adjustEvent.addCallbackParam ("content_id", "abc");
adjustEvent.addCallbackParameter ("view_point_index", "0");
adjustEvent.addCallbackParameter ("is_playing", "1");
adjustEvent.addCallbackParameter ("is_buffering", "3");
adjustEvent.addCallbackParameter ("is_vr", "2");
AdjustEvent.addCallbackParameter ("play_position", "123");
Adjust.trackEvent(adjustEvent);
}

It's written in this format. Is there a problem with my way of using it?

Also, is it absolutely impossible to use the Adjust SDK in the editor?

"A" app is already using Android Adjust SDK as an app that has been released on Google Play Store and has no problem.

The app I am currently producing with Oculus is trying to use the Adjust Dashboard used by "A", and only the invalid event token fail callback appears without sending the data I am sending.

**Comment by uerceg** [comment]
Setup in general looks okay to me.

Do you have event named `EnterMoviePlayScreen` in dashboard for your app? Maybe you are using SDK version which doesn't have support for usage of event names, but only tokens (if this is the case, using six characters event token from dashboard instead of `EnterMoviePlayScreen` name should do the trick).

And regarding Editor - yes. Adjust API is pretty much dead if you try to use it from Editor and will just print you message that SDK can't be used in Editor in case you try to ping Adjust API when running your app in Editor. All of SDK's logic is happening in native iOS and Android SDKs, so without actually running the app on iOS/Android device or simulator/emulator, our SDK won't even start or do a thing.

**Comment by Dong-Hwi-Lee** [comment]
I am writing a version of https://github.com/adjust/unity_sdk which is provided by this site.

Can the event name be replaced with a token in this version?

**Comment by uerceg** [comment]
I just checked with our support team, sorry, I was wrongly informed - please instead of name of the event, use six characters token when tracking it and it should work.

In case you have any further question(s), feel free to ping.

**Comment by Dong-Hwi-Lee** [comment]
If I check if there is a 6-digit token instead of the event name, I will test it using it and tell you

Thanks

**Comment by Dong-Hwi-Lee** [comment]
Instead of the event name, I use a 6-digit token to receive a success callback. Thank you.

There is one more question.

When using the callback parameter, the key and value are fixed as a string type. I tried to change the value to object type but it only gave an error.

For example, I want to send the value of the callback parameter in Int type. What should I do?

![Key_Value_String](https://user-images.githubusercontent.com/67088322/85492335-fa666280-b60f-11ea-817f-d5d24c9ba612.png)

**Comment by uerceg** [comment]
Hi @Dong-Hwi-Lee 

API for adding callback parameters is made so that key and value parameters are expected to be strings. You shouldn't try to change our SDK to allow injection of other types, but rather just make sure that you do conversion of key and value objects to string type in your app prior to calling **addCallbackParameter** method.

**Comment by Dong-Hwi-Lee** [comment]
Hi Adjust SDK Team

I have one more question.

Importing the Adjust SDK to my project automatically sends 자동적으로us-permission android:name="android.permission.permission.READ_PHONE_STATE" /> will be added.

I am uploading an app to Oculus Store, and when the permission is added, Oculus store rejects the app upload.

<us-permission android:name="android.permission.permission.READ_PHONE_STATE" /> Is this mandatory?

**Comment by uerceg** [comment]
Hi @Dong-Hwi-Lee 

Which permission exactly causes trouble for you? Adjust SDK is adding [these permissions](https://github.com/adjust/unity_sdk/blob/master/Assets/Adjust/Editor/AdjustEditor.cs#L252) automatically to your app upon building it.

**Comment by Dong-Hwi-Lee** [comment]
Hi Adjust SDK Team

Are those permissions required to use the Adjust SDK?

**Comment by uerceg** [comment]
```xml
<uses-permission android:name="android.permission.INTERNET" />
```
☝️ This one yes.

```xml
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
```
☝️ This one maybe not a bad idea. In theory if you're distributing your apps outside of the Play Store, I assume there's a good chance that devices which are going to run your app won't have Google Advertising ID available to be read by our SDK. Device identifiers are important to be read (at least some of them) for traffic which SDK is sending not to get rejected by our backend. With this permission SDK will have a way to fallback to some other identifiers, but in theory ultimate identifier SDK falls back onto if Google Advertising ID is not present is Android ID which, in theory, should be accessible on each device. Without this permission and without Google Advertising ID if SDK from that device tries to send install, it will get rejected.

```xml
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```
☝️ This one not really. Unless you are using your custom callbacks in our dashboard and are interested in getting `mcc` and `mnc` placeholders, then you need it. Otherwise, feel free to remove it.

```xml
<uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" />
```
☝️ This one (from what I understood) not. This one is used to get information about Google install referrer value which makes sense if you are distributing your app in Play Store. If not, feel free to remove it.

**Comment by Dong-Hwi-Lee** [comment]
Sorry for the confusion. This is the permission in question.

uses-permission android:name="android.permission.READ_PHONE_STATE" 

Is this mandatory?

**Comment by uerceg** [comment]
Our SDK is not adding that permission. 🤔 Not sure where did you end up picking it up. Link from above is our SDK's editor script (Android post build process) where we're adding only permissions I mentioned above.

**Comment by Dong-Hwi-Lee** [comment]
Yes I will check it again. 

Thanks for the help!

**Comment by Dong-Hwi-Lee** [comment]
Hi Unity Adjust SDK Team,

Currently I am developing with Unity and I am using Unity Adjust SDK.

In this regard, I received the following success callback for a specific event.

"Event tracked'bu4ah5' eventSuccessData.Message"
"2020-07-02T05:27:11.563Z+00 eventSuccessData."Timestamp"
"e0f61365d7e06c0411dcbf177ae71425 eventSuccessData.Adid"

However, on the customer side, it was said that the data of the event I sent was not actually received.

Even if I receive a success callback, can the above happen?

Also, are there any predictable errors??

Thank you.

**Comment by uerceg** [comment]
Message field of the response object in that callback should be present only when you are testing things with SDK environment set to sandbox. In production, message should not be present. Timestamp and Adid on the other hand should be there in both cases.

**Comment by ugi** [comment]
In case there's need to, feel free to reopen/comment.
