### ISSUE TITLE
AdjustSettings ScriptableObject is not saved after settings change

### ISSUE THREAD

**Issue by hdemmer** [adjust/unity_sdk#196]
Using v4.23.1.
The new AdjustSettings ScriptableObject is not written to disk after toggling anything on it.

Unity keeps the object in memory and the "Toggle ..." menu options change values (e.g. isiOS14ProcessingEnabled) on the memory instance but this is not actually saved until you save the current scene or project.

Even worse the "Check ..." menu options will report the unsaved value from memory.

This is at least confusing (because source control will not pick the change up until saved) or even dangerous (Unity crashes: the change will be lost).

You should not keep an Instance of the object in memory at all, imho. Load it the moment you want to read or change a value. Then save it if there were changes and unload the object.

So:
```
var instance = (AdjustSettings)AssetDatabase.LoadAssetAtPath("Assets/Adjust/Editor/AdjustSettings.asset", typeof(AdjustSettings));
// ... read or write value here

// if a value was changed:
EditorUtility.SetDirty(instance);
AssetDatabase.SaveAssets();
```

For now the workaround is to manually save the project (or scene) after changing the value.

**Comment by ugi** [comment]
Hi @hdemmer 

Thanks for writing and this was something we were thinking about, but didn't go with ti since from [suggested approach](https://github.com/adjust/unity_sdk/issues/190#issuecomment-692046167) from Facebook I didn't see that they were using `SaveAssets()` method. And from the documentation, seems that `SaveAssets()` method is used to save all assets marked as dirty, not just ours. I was trying to find an API to save only Adjust asset, but found none. And not sure if some random 3rd party dependency in user's app (Adjust SDK in this case) should have such a liberty and do potentially intrusive action of saving all game assets on its own. For this reason, this method call was not added.

Not sure what is best practice in this case, but it was intentionally built like this with above reasoning in mind. @martinrz2013, @shinji19, @donuts-mineshima, @wesclarkemag, @fliperamma (original requesters and upvotes), what's your take on this one?

**Comment by hdemmer** [comment]
I read the issue and support the new ScriptableObject approach. Although I would be okay with SaveAssets, you are probably right that it might cause headaches in other projects and it's cool that you're keeping your footprint low here.
Maybe it'd already be enough to add some text "Be sure to save your project to write these changes to disk" after using the "Toggle ..." menu options to prevent user error?

**Comment by ugi** [comment]
That's actually pretty cool idea. Adding it to our backlog and will be added to both toggle options in menu in next release. Thanks!

**Comment by dri-richard** [comment]
Can the file be saved to a relative location? Like other projects (and like Adjust itself does) we put 3rd party assets in a separate folder. The current implementation assumes the SDK has been put in the root of Assets.

**Comment by ugi** [comment]
Yeah, that was the unanswered part in [comment](https://github.com/adjust/unity_sdk/issues/190#issuecomment-698848376) I wrote. I was wondering if it makes sense to have it in SDK's `Editor` folder or not and then went with it since seemed to me that general idea from the issue was upvoted and it suggested that approach. And yes, with that in mind, we kinda hardcoded assumption that everyone follow our README when it comes to integration, which I assume is not always the case.

@dri-richard How would you envision this to work? To use some API to get current folder (where `AdjustEditor.cs` lives) and just append `AdjustSettings.asset` to it when loading/creating it?

**Comment by dri-richard** [comment]
I'd be happy for it to be in the current folder.
There may be other methods, but this works for me, returning "Assets/3rdPartyAssets/Adjust/Editor/AdjustEditor.cs"
```
var guids = AssetDatabase.FindAssets(string.Format("{0} t:script", "AdjustEditor"));
var assetPath = AssetDatabase.GUIDToAssetPath(guids[0]);
```

**Comment by ugi** [comment]
Sounds good, adding this to our next SDK update backlog as well. 👍 Will keep you guys posted on the progress and in case you have any other idea or suggestion, feel free to shoot.

**Comment by paradizIscool** [comment]
We're using adjust as a package to share between projects. So Assets/Adjust/Editor does not exist in the project, and Adjust/Editor folder is readonly.
We can patch this our package, but I guess that could be an issue for others.

**Comment by ugi** [comment]
@paradizIscool Does that mean that writing an **AdjustSettings.asset** inside of directory where **AdjustSettings.cs** resides is not possible to be done from editor script?

**Comment by ugi** [comment]
Hey guys,

Thanks one more time for suggestions and ideas. We have just released [v4.23.2](https://github.com/adjust/unity_sdk/releases/tag/v4.23.2) to address these ideas of yours.

Feel free to give it a shot and reopen/comment if something's still not working as expected.

Cheers!

**Comment by paradizIscool** [comment]
Does that mean that writing an AdjustSettings.asset inside of directory where AdjustSettings.cs resides is not possible to be done from editor script?
Yes

**Comment by ugi** [comment]
Gotcha. I mean, not really sure at this moment what to really do about it. It's hard sometimes to make quick'n'easy and yet solution which can cover all the edge use cases. I guess ideal way would be to allow users to somehow define folder in which they want to see asset being created / loaded, but maybe this can be something to consider for our next major SDK update.
