### ISSUE TITLE
No way to get the status of App-tracking authorisation

### ISSUE THREAD

**Issue by akapelon** [adjust/unity_sdk#200]
Hello,

We can see the wrapper for 
**requestTrackingAuthorizationWithCompletionHandler()**
to request app tracking authorization from the user, but there is no way to just get the current state of app tracking authorization...

In our project, we need to determine if the authorization is given or not _before_ we can display a custom dialog that will then lead to the native ios dialog.

(We can see other unity assets on the asset store offering both the **get** and the **request** but the adjust SDK only offers the **request** option... Are we missing something? )

**Comment by uerceg** [comment]
Hi @akapelon 

I don't think you're missing anything in here. We have created wrapper which is used to request tracking authorisation (and subsequently provide you with an answer once answer has been given) but we haven't made the getter for current tracking status for the given user. Calling the ** requestTrackingAuthorizationWithCompletionHandler** method for the first time ever will cause dialog to be displayed, but every subsequent time it kinda serves as "getter" for the tracking status since dialog gets to be displayed only once. So in theory, one can build some kind of a logic around that single method to have it as some kind of a getter (for example storing information inside of your app that you got response from your user to the dialog and then based on this flag, you can know that every subsequent call to that method will just have "getter" purpose).

But I also agree that approach with just having a getter is way cleaner. Will check with our product team about adding this feature to public API. Will keep you posted.

**Comment by uerceg** [comment]
@akapelon Expect this to be available in our next Unity SDK update. No firm ETA on it, but aiming to have it live next week.

**Comment by akapelon** [comment]
That is great news. Thank you!

**Comment by akapelon** [comment]
Just FYI, we are trying the implement the strategy mentioned here on your blog for our Unity Game.
https://www.adjust.com/blog/getting-the-opt-in/

"We highly recommend brands use a pre-permission prompt to request consent prior to triggering the iOS pop-up."

So the **getter** is not just useful, but essential for the pre-prompt in order to show or not show the custom dialog without displaying the native permission dialog first.

**Comment by uerceg** [comment]
Last week, we released an update to our native iOS SDK where we have exposed this getter and we're gonna be working on Unity SDK update next week in which we're gonna provide this getter in Unity SDK as well. Will keep you posted.

**Comment by uerceg** [comment]
Aiming to have update live this week.

**Comment by uerceg** [comment]
And it's live: https://github.com/adjust/unity_sdk/releases/tag/v4.26.0

Method you're looking for is this one: https://github.com/adjust/unity_sdk/blob/master/Assets/Adjust/Unity/Adjust.cs#L523

Feel free to give it a try and let us know if it worked well for your use case.

Cheers!

**Comment by akapelon** [comment]
Well we've sort of implemented this now natively in our app...
But it looks fine!

Maybe at some point we'll hook up this adjust call instead of ours.

Thank you!
