### ISSUE TITLE
XCode Minimum Requirement

### ISSUE THREAD

**Issue by ttermeer-reboundcg** [adjust/unity_sdk#212]
The documentation could use a XCode version requirement. `AdServices.framework` does not seems to be available on XCode 12.2 which is currently the maximum version supported by Unity Cloud Build.

Either this should be added in the documentation or `AdServices.framework` should be made optional like other iOS 14 speicific framework. There is still a `IsiOS14ProcessingEnabled` for some framework but this is does not include the new `AdServices.framework` .

**Comment by uerceg** [comment]
Hi @ttermeer-reboundcg 

Makes sense. Least we can do is to update README to stress minimal Xcode (native Apple's iOS SDK) requirement in order to be able to use frameworks such as **AppTrackingTransparency.framework** and **AdServices.framework** and we're gonna do that, thanks for the suggestion.

But definitely more elegant solution would be to somehow allow users configure some setting which would then instruct our iOS post build process which frameworks it should link and which one to skip. We'll think about this for some of the future releases, sounds like nice enhancement idea.

Cheers

**Comment by LaCreArthur** [comment]
Hi there, I have a similar issue with Unity Cloud Build
```23262: ▸ Linking UnityFramework
23263: ❌;  ld: framework not found AdServices
23264: ❌;  clang: error: linker command failed with exit code 1 (use -v to see invocation)
23265: ** ARCHIVE FAILED **
23266: The following build commands failed:
23267: 	Ld /BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-cptzktueeilqksgnkfqsejjnkjhh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/UnityFramework.framework/UnityFramework normal
23268: (1 failure)
23269: Exit status: 65
23270: Maybe the error shown is caused by using the wrong version of Xcode```
Unity Cloud Build XCode version is still 12.2 as for today, so this is the problem ? Did you find a solution or workaround  @ttermeer-reboundcg ? I need to use cloud build, having no access to a physical Mac myself :/

**Comment by LaCreArthur** [comment]
Nevermind, found how to build with xCode 12.4, on Unity Cloud Build, in the Signing Credentials settings, by default the xCode version is set to "latest" which is using 12.2 , however there 12.4 can be set manually. No more issues :)
