### ISSUE TITLE
 AdServices framework Error after SDK Update

### ISSUE THREAD

**Issue by MKUpjers** [adjust/unity_sdk#214]
Hello,

i wanted to update the SDK to the newest Version (4.27.0) from Version 4.23.0. to be ready for iOS 14.5 and the new Tracking Workflow. But since the update i always get a linker error in Xcode (Version 11.3.1) which tells me, that the AdServices framework can't be found.

Is there any workaround for this? 

The normal requesting of the iOS Trackingpopup via [Unitys Beta package](https://docs.unity3d.com/Packages/com.unity.ads.ios-support@0.1/manual/index.html) worked fine before.

**Comment by uerceg** [comment]
Hey @MKUpjers 

Sorry for a delay. I'd say that's probably expected behaviour since Apple introduced that API as part of their iOS SDK 14.3 (as you can see in their [docs](https://developer.apple.com/documentation/adservices/aaattributionerror?language=objc)). So I'd say that if you want to use that feature, you should update your Xcode version. On the another side if you don't need that, then feel free to remove `AdServices.framework` from your Xcode project.

**Comment by MKUpjers** [comment]
Updating our Mac and XCode Versions fixed the problem. Thank you very much
