### ISSUE TITLE
Adjust SDK Unity - Android 12 (SDK 31)

### ISSUE THREAD

**Issue by rau-infinity** [adjust/unity_sdk#248]
Hi all,

We're seeing quite a lot of crashes on Google Play Console in particular with devices running on Android 12 (SDK 31). We also use Backtrace for monitoring our crashes. From the data that we're capturing, we seem to be getting an abort error with this message

<img width="833" alt="image" src="https://user-images.githubusercontent.com/109504613/183009347-4356c744-2d56-43cd-bd47-3df705ca465a.png">

Here's a list of the stack trace (no symbols unfortunately)

![image](https://user-images.githubusercontent.com/109504613/183009443-052a2641-d67c-467d-9bdb-7adf2dd1276d.png)

From these crashes, we were using 4.29.7 of the Adjust SDK, I'm just upgrading to latest now. Would this have been addressed in the most recent updates?

Also, is that message informational, or is our configuration for retail/production mode not set up correctly?

**Comment by uerceg** [comment]
Hi @rau-infinity,

Too bad the stack trace contains no symbols, but the initial screenshot you shared does help us to narrow down where this might be coming from.

That log line is being printed natively from [here](https://github.com/adjust/android_sdk/blob/48a005f4424dc96a12d94b7e1d1d61043712a94d/Adjust/sdk-core/src/main/java/com/adjust/sdk/AdjustConfig.java#L267) (effectively executing [this](https://github.com/adjust/android_sdk/blob/48a005f4424dc96a12d94b7e1d1d61043712a94d/Adjust/sdk-core/src/main/java/com/adjust/sdk/Logger.java#L112) under the hood).

As you can see, it's a simple log command which is trying to print the warning level log.

Could it be that your release build of an app doesn't treat this as expected and that crash happens due to that fact?

If that doesn't ring any bells, there is a way to bypass printing of that line in production mode:

- Set log level on `AdjustConfig` to suppress.
- Make sure to initialize `AdjustConfig` instance with [this](https://github.com/adjust/unity_sdk/blob/977bbfbec5358df0a944862e807429ef04223caf/Assets/Adjust/Unity/AdjustConfig.cs#L74) constructor and pass `true` for the third parameter value.

If you have any other comments / questions, feel free to ask.

**Comment by rau-infinity** [comment]
Hi @uerceg,

Thanks for responding! From what I can gather we are initialising it to `AdjustEnvironment.Production` and setting the suppression flag to `true` for our shipping builds. With that flag set to `true` though, we shouldn't be seeing that log though right?

**Comment by uerceg** [comment]
Correct. If that flag is set to true in `AdjustConfig` instance before you paas it to `Adjust.start` method call, that line should not be printed. Are you seeing it being printed if you try this setup locally?

**Comment by uerceg** [comment]
Hi @rau-infinity,

Any update on this one?

**Comment by rau-infinity** [comment]
Hi,

After further digging around, it seems that the log is the last thing that
gets reported, so a bit of false information I believe. Upon looking up the
issue, others had experienced something similar, but it was mostly to do
with a Unity Engine audio initialisation bug on Android.

I'm happy to close the issue for now as there shouldn't be anything that
needs further investigation into for the Adjust SDK.

Cheers,
Richard
