### ISSUE TITLE
OpenUPM Package Contains "Example" Folder - Causing Issues

### ISSUE THREAD

**Issue by jtigner-sg** [adjust/unity_sdk#311]
### Package Information
* **Installation Method**: OpenUPM - https://openupm.com/packages/com.adjust.sdk/
* **Adjust Version**: 5.0.2
* **Unity Version**: 2022.3.20f1

### Problem Statement
* The package contains an _Example_ folder that has a Scene, Prefab, and Script.
* The folder does not have it's own Assembly definition for Editor-only so it ends up in the default Unity assembly.
* The scene cannot be opened - ![image](https://github.com/user-attachments/assets/c405e73e-553d-4921-904f-6679dc098470)
* The prefab reports a missing script - ![image](https://github.com/user-attachments/assets/c83dfd4b-99d0-4f78-a592-5ab3b6977fdb)

### Suggestion
* The package should use the UPM capability to supply _Samples_ - https://docs.unity3d.com/Manual/cus-samples.html

**Comment by uerceg** [comment]
Hey @jtigner-sg, @JRGreenfield,

Thanks for bringing this up. I wanted to ask do you have any use case for what's inside of the `Example` folder inside of our package? Asking because we're considering is to actually remove it from our Unity package completely. In case there is some benefit in having a script which showcases how Adjust SDK can be used (pretty much the content of the `Example` folder), we can always extract that into a separate directory in the repo as a reference and still keep it away from the plugin content itself.

Looking forward to hearing back from you.

Cheers.

**Comment by uerceg** [comment]
At the end, we went with what we had in mind (from the comment above). As of [v5.0.4](https://github.com/adjust/unity_sdk/releases/tag/v5.0.4), this should not be the issue anymore. We might consider examples being part of the package in the future in case there's demand for such thing, but we believe that having example scene which uses the SDK in the repo should be enough.

I will be closing this issue, but in case you still have some questions / comments, feel free to comment / reopen.

Cheers

**Comment by JRGreenfield** [comment]
This works for me. Thanks!
