### ISSUE TITLE
Integrated confirmed that after the first log normal?

### ISSUE THREAD

**Issue by sedrion** [adjust/unity_sdk#55]
"SendMessage: object Adjust not found!"

Is there any information related to this summit together with the contents of touch eroding ?

*only ios

**Comment by nonelse** [comment]
In what scenario does this happen? we test it in our example app without problems

**Comment by sedrion** [comment]
1. unitypackage
2. integration
3. adjust start function call
4. "SendMessage: object Adjust not found!"

*Events are logged correctly

**Comment by nonelse** [comment]
I wasn't able to reproduce it. Can you give more information about your system, OS, unity version? maybe you can email us at support@adjust.com if you want more privacy about it.
I found this issue for another project from someone with a similar [problem](https://github.com/soomla/unity3d-store/issues/318). Their solution was to include the proper prefab in the scene. Did it help?

**Comment by sedrion** [comment]
Without using the "Adjust class" offered "AdjustManager class" is made ​​use of to .

Please make sure gon ever need to change the "sceneName" in AdjustConfig class setAttributionChangedDelegate Function.

default = "Adjust"
In my case is = "AdjustManager"?

**Comment by nonelse** [comment]
the `sceneName` is set for the attributionChanged delegate. It's a callback from the native side to a unity scene. By default, because we provide the `Adjust.prefab`, that is the default name. If you are using our sdk in an another scene, then you have to set the different name to get the attribution changed callback.
The mechanism used is `UnitySendMessage`, so it is likely that is the reason of the error message.
Let us know if this solved the problem.

**Comment by sedrion** [comment]
테스트 완료 되었습니다. 해당 로그는 더이상 발생되지 않습니다. 답변 감사드립니다.
