### ISSUE TITLE
Post process step hangs indefinitely on build

### ISSUE THREAD

**Issue by jcomo** [adjust/unity_sdk#77]
When running a build, there is a post process trigger for both android and iOS that spawn a python process to modify some metadata in the respective platform. There seems to be an issue (maybe only in our case) with the way the Process API is being used.

This part of the script: https://github.com/adjust/unity_sdk/blob/master/Assets/Editor/AdjustEditor.cs#L165 assumes that the python script is executable which, by default upon download the SDK, is not. Changing those lines to look like this

```cs
proc.StartInfo.FileName = "python";
proc.StartInfo.Arguments = Application.dataPath + pathToScript + " " + arguments;
```

fixes the issue and allows the build to complete successfully, but I'm not sure I can articulate why with my limited knowledge of the Process API. Have you seen this issue before?

**Comment by uerceg** [comment]
Hi @jcomo 

Occasionally we were getting comments from users about similar issue and thank you for your suggestion how to fix this. It will be tested and most probably added to our upcoming 4.8.0 release.

This is the current PR for that version: https://github.com/adjust/unity_sdk/pull/75

In there, we have decided to completely remove Python post build scripts exactly because of this and all different kinds of issues which were getting reported from users from different operating systems and even different apps which were handling the opening of `.py` files, etc.

Anyway, as of 4.8.0, our unity package for Unity 5 will not contain Python post build scripts anymore and issues like this should not be happening.

Unity package for Unity 4 will keep having them, due to some missing API in Unity 4 which doesn't allow us to remove them and keep the same like Unity 5 package. But, thank you one more time for this change suggestion, will be tested with unity package for Unity 4 and if everything looks fine, will add it to upcoming release.

Cheers

**Comment by jcomo** [comment]
Thanks @uerceg! Yes, an even better solution would be to move it to C# entirely, I agree. Sorry for not taking a look at the PR section before posting this issue. Do you have an ETA on the release of 4.8.0?

**Comment by uerceg** [comment]
Hi @jcomo 

A but of versioning change, but update is live now: https://github.com/adjust/unity_sdk/releases/tag/v4.10.0

Give it a try and let me know if it helped you with your issue.

Cheers

**Comment by jcomo** [comment]
Thanks! We'll give it a shot

**Comment by uerceg** [comment]
Feel free to reopen if issue is still there.

**Comment by jcomo** [comment]
We actually cherry picked the build scripts off from the new version and were using those instead so I'm confident this with solidify the fix
