### ISSUE TITLE
TearDown is not exposed

### ISSUE THREAD

**Issue by brianclanton** [adjust/unity_sdk#80]
I can see that tear down functions were added in newer versions of the Adjust native SDKs, but this functionality has not been exposed in the Unity wrapper. It would be great to have that made accessible for the next release. @uerceg

**Comment by uerceg** [comment]
After discussions we had on this topic, this is not something we will do in v4 since we do consider it dangerous and in addition to that, it would require quite a bit of SDK refactoring. If we find a safe fool proof way for this to be exposed in v5, we might add it, but at this moment, we do not plan to add it. Once v5 design becomes a topic, I'll update in here if we'll go with it. Sorry for not being able to add this feature at this time to our SDK. Cheers!
