### ISSUE TITLE
Link error on xcode build

### ISSUE THREAD

**Issue by ackell80** [adjust/unity_sdk#84]
unity3d version is 5.3.6f1
xcode version is 7.3.1 (7D1014)

After applying adjust unity3d plugin, following error occurs during the builds in xcode.

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ADJEvent", referenced from:
      objc-class-ref in AdjustUnity.o
  "_OBJC_CLASS_$_Adjust", referenced from:
      objc-class-ref in AdjustUnity.o
     (maybe you meant: _OBJC_CLASS_$_AdjustUnity)
  "_OBJC_CLASS_$_ADJConfig", referenced from:
      objc-class-ref in AdjustUnity.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please review the message and I would be appreciate if you help me to resolve this issue.
Thank you in advance.

Best,
-Ackell

**Comment by uerceg** [comment]
Hi @ackell80,

And sorry for a bit delayed answer.

Can you please tell me which `unitypackage` version of our Unity SDK are you using?

Cheers

**Comment by petererikson-rovio** [comment]
We are having the same issue 

Xcode7.2.1
Unity 5.4.0p4
Adjust Unity SDK 4.10.2

Cheers,
Peter

**Comment by petererikson-rovio** [comment]
Please ignore my previous post.

It was a local version control issue. We had *.a files in our ignore filter.

**Comment by uerceg** [comment]
Aye. 👍 Thanks for the update.

@ackell80 ☝️ Anything similar like this maybe in your case? Are you still facing this issue?

**Comment by uerceg** [comment]
@ackell80 Any update on this?

**Comment by SangCrowdstar** [comment]
try removing -ObjC in linker flag. That did it for me but not sure if it affects anything else

**Comment by uerceg** [comment]
Yeah, for most of the cases yes. But depends from what do you have in your other linker flags. Do you maybe already have -force_load flag in there? How does your other linker flags list look like?

**Comment by SangCrowdstar** [comment]
my other linker flag has the following:
-weak_framework
CoreMotion
-weak-ISystem
$(inherited)
-lsqlite3
-lz

if it is needed, how do I solve the duplicated symbol issue?

**Comment by uerceg** [comment]
`-ObjC` linker flag is needed in order for our native iOS categories to be properly loaded. You can give it a try with not adding this linker flag. Test is fairly simple: Remove that flag from your Xcode project settings and run your app. As soon as adjust SDK gets started, if you see in the logs that it initialised properly, all good. If on the other hand it didn't, you'll see exception message which will probably look something like this: https://github.com/adjust/ios_sdk#ts-categories

Lemme know how did the test go.

Cheers

**Comment by SangCrowdstar** [comment]
Turns out its not Adjust issue. Nanigans SDK has duplicated libraries, it was never detected because  we never added -ObjC linker flag. So after I removed the duplicated libraries from Nanigans and re-added the -ObjC flag, everything works fine now. 

Thanks.

**Comment by uerceg** [comment]
Great, glad it worked. Thanks for letting us know about the solution for the future reference.

Cheers

**Comment by brandesign** [comment]
Hello,

sorry to comment on a closed Ticket but I have the same problem right now. The build fails with:

> Undefined symbols for architecture arm64:
>   "_kSecAttrAccessGroupToken", referenced from:
>       -[ADJActivityState assignUuid:] in AdjustSdk.a(ADJActivityState.o)
>       -[ADJKeychain setValue:forKeychainKey:inService:] in AdjustSdk.a(ADJKeychain.o)
>       -[ADJKeychain keychainItemForKeyNew:service:] in AdjustSdk.a(ADJKeychain.o)
>       -[ADJKeychain setValueWithStatus:forKeychainKey:inService:] in AdjustSdk.a(ADJKeychain.o)
>       -[ADJKeychain wasWritingSuccessful:forKeychainKey:inService:] in AdjustSdk.a(ADJKeychain.o)
> ld: symbol(s) not found for architecture arm64

How can I find duplicated libraries and how can I remove them?

Thanks.

**Comment by uerceg** [comment]
Hi @brandesign 

I guess you are using Xcode 7 with your Unity IDE. Can you update Xcode to 8 and retry?

Cheers

**Comment by brandesign** [comment]
Hi @uerceg 

Thanks, that did the trick.

Cheers

**Comment by mingyu92623** [comment]
hey ugi ，

a client got same problem  and he have remove the-ObjC linker flag and his xcode version is 9. but he still have this problem, what should they do about this : 

![image](https://user-images.githubusercontent.com/25768439/36889560-7b08db4a-1e35-11e8-8fd3-e7f7eedda42f.png)
![image](https://user-images.githubusercontent.com/25768439/36889568-8868eac8-1e35-11e8-85e6-f7a13bcfe9db.png)
![image](https://user-images.githubusercontent.com/25768439/36889571-8bf35d4a-1e35-11e8-8a93-6fb7104ffa4e.png)

**Comment by Elzquiem** [comment]
Hello,

I'm sorry to comment on a closed Ticket, but I encounter the same issue (by ackell80) right now.
I'm working on a recovered project for a mobile game, both on Android and iOS, but I'm new on iOS systems and Mobile Apps practices (ads, app purchase and tracking). 

Mu predecessor told me that we use the Adjust plugin to take care of the tracking part and breifed me quickly on XCode, which is the first time I use it. He especially warned me about the "-ObjC" parameter in the "Other linker flags". I let Unity build the XCode project, and only set the apple ID in order to try a dev build. But sadly, I have the mentioned issue when trying to build my Unity project on iOS, as seen on the following screenshot :

<img width="880" alt="link error" src="https://user-images.githubusercontent.com/5836951/52068503-141b8b80-257d-11e9-9696-37fa894a1ada.png">

I think, from what I understood, that is a linking problem and it's the Adjust SDK library that is not taken in account when building. But after many tries, operations and searches, I'm still stuck on the issue. Did I do something wrong when configuring the project or is it just a lack of iOS knowledge ? I wanted to ask before trying to [update the SDK as a last ressort](https://github.com/adjust/unity_sdk#sdk-add) since I might brake the current prod if I do it recklessly.

I also question myself about the "[AdjustScript] Import Settings" as seen on the screenshot :

<img width="721" alt="adjust import settings" src="https://user-images.githubusercontent.com/5836951/52068539-2695c500-257d-11e9-8f04-d2992b3ffa92.png">

It seems that it needs to be set in order to work correctly but I didn't find any informations on this specific inspector. I've checked all iOS scripts and all of them have either "Any Platform", "iOS" or "Android" (when on Windows) checked (Seems odd since they are iOS scripts). Do I need to configure anything on those settings in particular, or is this the "default" configuration when the plugin has been imported ?


Here are the versions of the project I recovered :
- Using macOS Mojave, version 10.14
- Unity3D version : 2018.1.4f1 (64 bit)
- Xcode version : 10.1 (10B61)
- Adjust SDK : I think it's 4.11.4 (I've checked the AdjustiOS script and found the following line : private const string sdkPrefix = "unity4.11.4";)

Additional informations : 
- My current iOS Deployment target is 8.0 . I tried to increase this number, but without success ;
- The adjust settings for the project (token + dashboard project) have not been created yet (But I don't think that would be an issue for building on iOS) ;
- My "Other linker flags" are the following : $(inherited) -weak_framework CoreMotion -weak-ISystem -ObjC
- I cleaned the build and deleted ~/Library/Developer/Xcode/DerivedData/* but nothing changed ;
- [I had this warning on the Mac](https://support.apple.com/en-us/HT208436) but I don't know if it can be tied to the issue ;
- According to Unity, [it's safe to ignore the libiconv.2.dylib](https://forum.unity.com/threads/no-reference-to-libiconv-2-dylib-on-xcode-7.353999/) ;
- iOS post build process is working correctly : required frameworks and -ObjC are correctly added, as seen on the screenshot below.

<img width="1121" alt="project_libraries" src="https://user-images.githubusercontent.com/5836951/52068559-301f2d00-257d-11e9-9808-ed251926518c.png">

Thanks a lot for your consideration.
