### ISSUE TITLE
Problems logging custom events and revenue

### ISSUE THREAD

**Issue by andres2000** [adjust/unity_sdk#92]
Hello! We are using the Unity SDK and getting all the user attribution logged correctly. We don't seem to be able to log any custom events or revenue, though.

We have added several different calls like this one:
    Adjust.trackEvent (new AdjustEvent ("registrationAttempt"));

and this other format to try to log purchases (where 'realPrice' is a double and 'currency' a string):
   AdjustEvent adjustEvent = new AdjustEvent ("realMoneyTransaction");
   adjustEvent.setRevenue (realPrice, currency);
   Adjust.trackEvent (adjustEvent);

In the Adjust dashboard, in Column Selection, we see 2 of these events, but they never show any data, and all other events are missing. We are using Unity 5.4.1p2, and SDK version is 4.1.3, I believe (at least that's what the sdkPrefix const is set to). Our pricing plan is supposed to include logging of in-app events.

Are we doing something wrong? Thank you in advance!

**Comment by uerceg** [comment]
Hi @andres2000 

Where are you checking for logs about tracked events? Are you checking the device logs? If you try your app with our SDK in sandbox environment and log level set to `verbose`, you'll be able to see stuff being tracked.

And another question - code from above you showed, `registrationAttempt` and `realMoneyTransaction` strings are just your examples, right? Because in there, you should use six characters event token for each event, not their dashboard names.

**Comment by andres2000** [comment]
Ah, got it! I'm very sorry, I didn't realize I had to input the token instead of the event name. I'll try that out. Thank you for the quick reply!

**Comment by uerceg** [comment]
No problemo. Glad we solved it! 👍 

Cheers!
